### ISSUE TITLE
Benchmark BW6 on mobile

### ISSUE THREAD

**Issue by kobigurk** [celo-org/zexe#50]

**Comment by kobigurk** [comment]
Benchmarks done by @mrsmkl are available here: https://docs.google.com/spreadsheets/d/1-IrDbAzfzehcjgnXQ8sPy9Gs1A8DhIWeLhFmYrdQD8Q/edit?usp=sharing

This is for a circuit with 222481 constraints on BW6

**Comment by asaj** [comment]
@mrsmkl is there anything else we need to do here or can we close?

**Comment by mrsmkl** [comment]
I cannot think of anything to do anymore...
